release:
	@echo "Stub release"
debug:
	@echo "Stub debug"
utest:
	@echo "Stub utest"
run_utest:
	@echo "Stub run utest"
run_itest:
	@echo "Stub run itest"
clean:
	@echo "Stub clean"
all:
	@echo "Stub all"
